<div class="container-fluid mt-2 pt-5" style="margin-top: 100px;">
    <div class="realizujeme">
        <h1 class="text-center mb-5">Realizujeme montáže:</h1>

        <!-- Karty s produkty -->
        <div class="row row-cols-1 row-cols-sm-3 row-cols-md-5 g-3 me-3">
            <!-- Venkovní žaluzie -->
            <div class="col">
                <div class="card h-100 me-3">
                    <img src="<?= url('images/services/exZaluzie.jpg') ?>" class="card-img-top" alt="Venkovní žaluzie">
                    <div class="card-body">
                        <h4 class="card-title">Exteriérové žaluzie</h4>
                        <p class="card-text">Chrání Vaše okna před nepříznivým počasím a v zimě zabraňují úniku tepla z domu.</p>
                    </div>
                </div>
            </div>
            <!-- Venkovní rolety -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/VenkovniRolety.jpg') ?>" class="card-img-top" alt="Venkovní rolety">
                    <div class="card-body">
                        <h4 class="card-title">Exteriérové rolety</h4>
                        <p class="card-text">Zajišťují zastínění, termoregulaci i snížení hluku.</br>Možnost provedení jako předokenní nebo screenové rolety.</p>
                    </div>
                </div>
            </div>
            <!-- Pergoly -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/pergola.jpg') ?>" class="card-img-top" alt="Bioklimatické pergoly">
                    <div class="card-body">
                        <h4 class="card-title">Bioklimatické pergoly</h4>
                        <p class="card-text">Zaručí pohodlí a krásu celé zahrady. Díky otočným lamelám na dálkové ovládání buď stíní nebo chrání před deštěm. Možno realizovat i jako Carport.</p>
                    </div>
                </div>
            </div>
            <!-- Markýzy -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/markyza.jpg') ?>" class="card-img-top" alt="Markýzy">
                    <div class="card-body">
                        <h4 class="card-title">Markýzy</h4>
                        <p class="card-text">Efektivní stínění pro Váš domov, zahrady a terasy, které vás ochrání před slunečními paprsky.</p>
                    </div>
                </div>
            </div>
            <!-- Plisse -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/plisse.jpg') ?>" class="card-img-top" alt="Plisse rolety">
                    <div class="card-body">
                        <h4 class="card-title">Plisse rolety</h4>
                        <p class="card-text">Skládaná látková žaluzie poskytne soukromí i zastínění Vašeho domova.</p>
                    </div>
                </div>
            </div>
        </div>

        <div class="row row-cols-1 row-cols-sm-3 row-cols-md-5 g-3 mt-4 me-3">
            <!-- Vnitřní žaluzie -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/inZaluzie.jpg') ?>" class="card-img-top" alt="Vnitřní žaluzie">
                    <div class="card-body">
                        <h4 class="card-title">Vnitřní žaluzie</h4>
                        <p class="card-text">Efektivní zastínění v horizontálním i vertikálním provedení nebo jako střešní žaluzie.</p>
                    </div>
                </div>
            </div>
            <!-- Sítě -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/site.jpg') ?>" class="card-img-top" alt="Sítě proti hmyzu">
                    <div class="card-body">
                        <h4 class="card-title">Sítě proti hmyzu</h4>
                        <p class="card-text">Už žádný otravný hmyz ve Vašem domově. Pořiďte si sítě do oken i dveří a to i v provedení plisse.</p>
                    </div>
                </div>
            </div>
            <!-- Látkové rolety -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/latkoveRolety.jpg') ?>" class="card-img-top" alt="Látkové rolety">
                    <div class="card-body">
                        <h4 class="card-title">Látkové rolety</h4>
                        <p class="card-text">Pohodlné stínění v různých variantách. Rolety lze namontovat i do střešních oken. Vybrat si můžete také zatemňovací rolety.</p>
                    </div>
                </div>
            </div>
            <!-- Screenové rolety -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/screenRolety.jpg') ?>" class="card-img-top" alt="Screenové rolety">
                    <div class="card-body">
                        <h4 class="card-title">Screenové rolety</h4>
                        <p class="card-text">Dodávají domům moderní vzhled a zajišťují ochranu proti slunečnímu záření. Lze je provést jako přiznané, podfasádní, do pergol nebo jako stínění pro verandy a zimní zahrady.</p>
                    </div>
                </div>
            </div>
            <!-- Posuvné zasklení -->
            <div class="col">
                <div class="card h-100">
                    <img src="<?= url('images/services/zaskleni.jpg') ?>" class="card-img-top" alt="Posuvné zasklení">
                    <div class="card-body">
                        <h4 class="card-title">Posuvné zasklení</h4>
                        <p class="card-text">Krásný designový prvek, který Vám umožní používat Vaši pergolu či balkon celoročně.</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>